library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(DT)
library(matrixStats)
#library(xlsx)
#library(rcompanion)
#library(questionr)
library(ggplot2)
#library(DescTools)
library(psych)
#library(psycho)
#library(fpc)
#library(cluster)
library(clustree) # clustree likes to be loaded
#library(factoextra)
#library(NbClust)
#library(GPArotation)
#library(ggraph)
#library(scam)
#library(leaps)
#library(bestglm)
#library(sjPlot)

# Hidden requirements from other packages - Shiny would like to know them
requireNamespace("ggraph", quietly = TRUE)
requireNamespace("GPArotation", quietly = TRUE)
requireNamespace("Rcsdp", quietly = TRUE)

source("functions_helper.R", encoding = "utf-8")
source("functions_ui.R", encoding = "utf-8")