library(shiny)
library(shinyWidgets)
library(DT)
#library(xlsx)
#library(rcompanion)
#library(questionr)
library(ggplot2)
#library(DescTools)
library(psych)
#library(psycho)
#library(fpc)
#library(cluster)
#library(clustree)
#library(factoextra)
#library(NbClust)
#library(GPArotation)

source("functions.R", encoding = "utf-8")
source("ui_elements.R", encoding = "utf-8")